version: '3'
services:
  app:
    image: node:alpine
    container_name: "vue_app"
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
