version: '3'
services:
  app:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/