version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  node:
    image: node:alpine
    container_name: "vue_app"
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
