version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue
    container_name: "vue_app"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
